CFLAGS = -std=c99 -c
CC = clang

all: dweight.c dweight2.c celsius.c pun.c
	$(CC) dweight.c -o dweight.o
	$(CC) dweight2.c -o dweight2.o
	$(CC) celsius.c -o celsius.o
	$(CC) pun.c -o pun.o
	$(CC) *.c -o *.o
